### PR TITLE
Scoped config

### PR DESCRIPTION
**Pull request by Paulloz**
Hi!
Thought it might be cool to be able to use language specific configuration. I.E. I wanted `autoAddingHeaderEnabled` to be `true` but deactivate it for **Markdown** files.
I just scoped every `atom.config.get` call.

### CODE REVIEW

**Comment by guiguan** [comment]
Awesome, thank you Paul!

**Comment by guiguan** [comment]
@Paulloz how do we set those language specific configurations? we need an option, such as "whitelist", in file-header setting right?

**Comment by guiguan** [comment]
@Paulloz I ended up adding an option in settings to let user set a list of ignore scopes instead.

**Comment by Paulloz** [comment]
@guiguan You can configure everything language specific directly in your `config.cson` file.
```coffeescript
"*":
    "file-header":
        autoAddingHeaderEnabled: true
        email: "..."
        realname: "..."
        username: "paulloz"
".gfm.source":
    "file-header":
        autoAddingHeaderEnabled: false
".plain.text":
    "file-header":
        autoAddingHeaderEnabled: false
```

**Comment by guiguan** [comment]
@Paulloz Oh, I see. I am used to the UI interface for settings. LOL. Do you still think it is still necessary to provide the scope settings given our new ignore list option in file-header settings?

**Comment by Paulloz** [comment]
Definitely, it's how you're supposed to handle settings.

**Comment by guiguan** [comment]
@Paulloz Alright, I integrated your scoped settings in v1.4.0. Check it out.

**Comment by Paulloz** [comment]
:+1:

**Pull request merged**
